# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md
  - contact.md

footer: 
style: dark # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)
title: Bashful
author: Richard Hall
description: >-
  hesitantly blogging while learning in the terminal
plugins:
  - jekyll-seo-tag
